### ISSUE TITLE
ClamAV prevents upload of file when not using the distribution on govCMS hosting platform

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#116]
Using recent build on a local laptop the anti virus protection fails and prevents the upload of a file into the system.

I have to go to configure clamav to ignore files when it is turned off. This may not be clear enough to a person playing with the distro in their own environment.

Not sure of the solution, whether it is disabled by default publicly, or the error message can be a bit more useful?

**Comment by typhonius** [comment]
ClamAV isn't enabled by default for the a default build of the govCMS distribution. In a local environment the user should keep Clam disabled or ensure that their environment has the ClamAV executable/daemon prior to enabling.

**Comment by fiasco** [comment]
This would be good to illustrate in a feature table of open source distro vs hosted offering

**Comment by aleayr** [comment]
If it isn't enabled by default, should it be part of the distro (possibly move to SaaS build/deploy process)? 

Added to a 'recommended' list of modules for people hosting off SaaS to consider installing themselves?

Thoughts?

**Comment by fiasco** [comment]
It certainly doesn't make sense to have clamAV enabled be default since it would also require the binary to be available. That being said, those on the PaaS offering would still benifit from it. I think this could be a good idea to split out platform modules from default distro modules so long as we could continue to track both in the same repository.
