### ISSUE TITLE
As a site builder / editor I want to be able to have my views tables to be mobile responsive

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#117]
e.g.

https://www.drupal.org/project/responsive_tables

Currently if you have views with tables, they are not mobile friendly... something like this that is D8 backport could be useful.

**Comment by aleayr** [comment]
Comment from @seanhamlin:

Can we get some use cases added to this request?

**Comment by aleayr** [comment]
@paulkilla Did you have any further info about this one? (originally internal, I've just imported it into here)

**Comment by paulkilla** [comment]
This came from Tim. Have a chat to him 

On 25 Nov 2015 3:16 pm, Adam Leayr notifications@github.com wrote:

@paulkilla Did you have any further info about this one? (originally internal, I've just imported it into here)

**Comment by fiasco** [comment]
Could we instead build the responsive capability into the supported base themes of govCMS?

**Comment by aleayr** [comment]
@fribibb I believe this was for the admin views correct? Should we sub-theme the admin theme and add this into that directly, or go down the module path? Thoughts @fiasco?

**Comment by fiasco** [comment]
This issue seems a little strange, shouldn't you want the entire theme responsive rather than just Views tables? While its not clear if the issue is regarding admin theme only, if it is, we'd be better off evaluating responsive admin themes rather than trying to maintain our own. We simply don't have the resources to deliver support for a maintained admin subtheme.

**Comment by fribibb** [comment]
ok, this was a fair while ago.. but the idea was to implement for _front_ end. 
The reason this wasn't just a theme level change, was because it involved more than just CSS (needs to add 'data-title' attribute on content render) and could benefit our 'white site'/base and custom themes if implemented as a module instead.

See:
http://elvery.net/demo/responsive-tables/#no-more-tables
for details and examples.

**Comment by cdriessen** [comment]
Not sure if this helps but we use a tablesaw library on our govCMS site to provide responsive tables - see example here https://www.communications.gov.au/what-we-do/bureau-communications-research/resources/key-facts

@srowlands implemented for us and may be able to provide more detail.

**Comment by aleayr** [comment]
Might leave this for the theme layer. If people want to implement responsive tables, they can do so via a JS library of their choosing.
