### ISSUE TITLE
Add some sort of content access control

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#143]
It would be useful to be able to restrict access to some content by role.

I am currently doing some work for an agency where some nodes need to be restricted.

I don't really have a specific solution in mind, it could be TAC, content access or something else.

**Comment by fiasco** [comment]
Hi @rooby, could you perhaps provide a bit more detail around the access control to content by role?
Certain roles can create, update, delete content? Or does it also include access to view? Is the access mapped by role to content type? Or is it by content metadata such as a taxonomy reference?

If you can provide the scenario, it helps give context to help make the decision of whether this is something that govCMS should support or not. Current, govCMS is designed for unclassified content. Basically, content that is publically available. By provided role based access, it suggests that you are hosting content that is not publically available but to authenticated and authorised personnel.

**Comment by rooby** [comment]
Yeah sorry, in this case I'm referring to node view permissions.

For example, only a certain role having access to some particular webforms or some node type that is only accessible to certain roles.

**Comment by rooby** [comment]
In my current case, content editors wouldn't have to select visibility of nodes regularly, it's just a couple that are always to be restricted, so it wouldn't need to be controlled by taxonomy.

**Comment by WebProject2015** [comment]
We would welcome improved role or group based access controls to help manage distributed authorship.  Essentially the user story we'd have would look something like this: 

As a content editor I want role based access so that only my team can edit the pages we own 

As the number of editors within an organisation grows, it becomes increasingly important to limit the authorship rights of your editors at a more granular level. A specific example is that there is an area of the site called "Rules", which is made up of standard page content types which fall into two categories "Current rules" and "New rules",  the people who make New Rules should not be able to edit the Current Rules, and the people who handle the Current Rules should not be able to edit the New Rules. It is not feasible to make these into different content type because New Rules can become Current Rules and the reverse is also possible.   As such, content editors should be given a role or added to a group which limits their authorship to only the nodes which are accessible to their role or group.  This is not to provide additional security in any way, but is to avoid confusion over ownership and authorship precendence by establishing clear content ownership designations. 

  Acceptance criteria:
1. Authenticated govCMS users can be given a designation which determines their access rights
2. That designation can be granularly determined on a per node basis. 
3. Users can not edit nodes for which they have no designated edit rights 
4. Publishers and Administrators can bypass access rights. 

We agree with rooby that we have no preference for a given module, technical implementation or control philosophy, as long as the above criteria are met. It would also be nice if you could assign large groups of nodes to a given designation at one time, something like url path or menu based designation.

**Comment by stooit** [comment]
@WebProject2015 check out the Workbench Access module which is already available in govCMS. It can be configured to meet the acceptance criteria you've outlined exactly.

This module is currently being used for business areas to have delegated access and control over a subset of content within a large site. Global administrators bypass those access restrictions.

@rooby this doesn't exactly match your use case (which sounds like you want to disable view access on selective nodes to certain roles) but you may find benefit there as well.

**Comment by teamglenny** [comment]
@WebProject2015 if you can't get down to the right level in SaaS for Workbench Access, spin up an Aquia Free, or Acquia Dev Desktop instance of govCMS, tinker with what you want the access control to look like, then submit a request via the Insight Portal.

@rooby the above may be the same for you if you are on the govCMS SaaS environment, if you are running govCMS on your own unfettered environment you should be able to access the module for a look as @srowlands has described.

**Comment by WebProject2015** [comment]
Awesome, we'll look into it. Thank you.

**Comment by rooby** [comment]
Yeah in this case I'm specifically interested in restricting view access, not edit access.

Workbench access is a good one to note for future though.

Currently I am working towards SaaS however there is the potential to move to PaaS in future so I have to be careful about taking liberties.

**Comment by dylan-oxide** [comment]
Just for some extra information, we used Panels to restrict view access per node to specific roles. We created a custom panel page for the specific node and set the Access to User:role. This restricts view access to only the roles selected. Whilst I would argue using Panels purely for access control is not a good solution, it is included in Panels so it can be utilised in the edge cases where admins need to restrict view access to particular nodes.

**Comment by WebProject2015** [comment]
We used Context to do something similar dylan, we could probably also use Context to achieve our goals stated above, however like Panels it is not an elegant access control solution.

**Comment by fiasco** [comment]
We see that some of this use case can be addressed with workbench access module which is in govCMS so we'll close this out. But if you need more complex access control, please open a new ticket and provide the context you need it in. Thanks.
