### ISSUE TITLE
Embedding form with <script> tags

### ISSUE THREAD

**Issue by Kirkwray** [govCMS/GovCMS7#157]
Hi
I'm trying to figure out a way to embed a frevvo form in to a page. The editor strips the code.

Has anyone had any experience or have any suggestions on how to get this to work?

script src="../../url/embed?container=true&amp;resize=true" type="text/javascript"></script

Thanks
Kirk

**Comment by dylan-oxide** [comment]
The WYSIWYG Filter doesn't allow script tags:
`The following elements cannot be whitelisted due to security reasons, to prevent users from breaking site layout and/or to avoid posting invalid HTML. Forbidden elements: <applet> <area> <base> <basefont> <body> <button> <embed> <form> <frame> <frameset> <head> <html> <iframe> <input> <isindex> <label> <link> <map> <meta> <noframes> <noscript> <object> <optgroup> <option> <param> <script> <select> <style> <textarea> <title>.`

You will have to use a text input format that doesn't have WYSIWYG Filter enabled. I believe by default Full HTML is the only text input format that will allow it.

**Comment by fiasco** [comment]
Its not a good idea to allow script tags in through a WYSIWYG editor as this is becomes a XSS vulnerability. Given this is for Frevvo, something govCMS is not likely to support, producing a token for this functionality is not likely either.

Your best option will be to create a node template file in the theme for the explicit node you which to embed the form on and place the script directly in the HTML output.

**Comment by aleayr** [comment]
Hi @Kirkwray, did any of @dylan-oxide or @fiasco's suggestions assist you in finding a solution?

Do you mind if I close this one off?

**Comment by Wongad** [comment]
Hi @aleayr, @Kirkwray is member of my team.

The suggestions offered by @dylan-oxide and @fiasco are valid. Looking at it we may probably do more research of what we could achieve.

On another note, I think issue #167 could really help us as well if any of the modules @srowlands suggested could be implemented.

This way if we create a node template for our Frevvo forms, we could easily embed them within our WYSIWYG area, which will help our non-technical users to easily use.

You could close this one off as we'll take note of the other issue ticket.

**Comment by aleayr** [comment]
Thanks, much appreciated, feel free to open it back up if the need arises :)
