### ISSUE TITLE
Menus disappear on 404 error pages

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#170]
When you hit a page not found page menus disappear from the site.

This happens if you disable the Search 404 module so you are actually having users hit the error pages.

It could be addressed by including the [404 Navigation](https://www.drupal.org/project/navigation404) module.

**Comment by fiasco** [comment]
404s are a huge issue from a performance stand point. For govCMS, sites migrating to us are always going to send 404s our way when the DNS flicks over. From a resource prioritization point of view, we'd rather focus on delivering 200 OK type pages rather than rendering 404s. Drupal's architecture agrees with this point of view and as such, doesn't render menus when its tasked with rendering a 404.

Could we instead issue a 301 or 302 and redirect to a 404 page which is served as a 200 OK? That way it would get cached and the performance burden for 404 pages would be much less.

**Comment by rooby** [comment]
Hmm I'm not really a fan of the redirect idea because you're giving an inaccurate response that could be bad for SEO and doesn't really benefit the user.

I think if the solution was going to be redirect based I would just enable the 404 search functionality again since you would then at least end up on a possibly relevant page.

The downside of redirects in general is that it breaks the link checker functionality for internal links, since they will never 404.

A solution to that could be configuring link checker to catch redirects, but then you also get false positives so the trade off is potential administrator frustration.

Maybe link checker could be patched to make it smarter in terms of playing nice with the 404 search redirects. That could be the best of both worlds.

**Comment by fiasco** [comment]
Our search 404 module default configuration has been under review lately. As you point out, redirecting off a 404 is not a good idea. Instead, we're now looking at a default behaviour that 404s and presents a pre populated search box on the page where a user can opt-in to search for the page that is missing.

This still will not address the lack of a menu however, we still agree that menus in 404 pages should remain out-of-scope for now.
