### ISSUE TITLE
Include [Print](https://www.drupal.org/project/print) module which render the page as PDF or printable HTML

### ISSUE THREAD

**Issue by Wongad** [govCMS/GovCMS7#192]
Under the available modules in govCMS, there's a **Print Services** (print_services) under Service Links - Services which _Add the support for Print module which render the page as PDF or printable HTML_

What is missing is the **Print module** which is required in order to use this.

The Print module can be found https://www.drupal.org/project/print for Drupal 7 and https://www.drupal.org/project/printable for Drupal 8, and they're actively maintained.

This will add on to the functionality of our website which we could remove additional PDF files and offer our users a PDF print version of the webpage.

**Comment by aleayr** [comment]
Thanks @Wongad, just want to flesh out this use case a little more.

What would be the advantage of doing this in your thoughts over simply printing the webpage (or using built in print to PDF options that some browsers have by default like Chrome)?

**Comment by Wongad** [comment]
Thanks @aleayr, here are a few use cases for enabling the PDF Print module:
1. Currently there's still a big percentage of users(40%) still using Internet Explorer or our sites, which does not has the PDF print option available. 
2. Not many users are savvy enough to understand that there's the PDF option available on Chrome.
3. Most government departments/agencies only have Internet Explorer as default.
4. The PDF module is able to provide consistency on the PDF output, rather than relying on the Browser's setting.
5. Creating publications always rely on the created PDF then transfer to webpages, if this can be reverse to creating webpage then PDF will create a different work process in publications. Taking web accessibility as the main driver.

Let me know if you require more information or details.

**Comment by mgdhs** [comment]
One of our team members evaluated this module's functionality and we decided against using it for a few reasons:
- It can be achieved with a proper (simple and short) print CSS - think of it as part of a responsive design, where a page is simply one more device.
- A dedicated print page is old school and has been phased out in the industry.
- How do you manage the analytics and navigation between print and non-print, and maybe even separate mobile pages. What happens when someone links or searches and gets directly to the print page?
- "[Users spend most of their time on other websites](http://sivers.org/quirks)". If this is a browser or software function that a small percentage of users need, they can manage that themselves. This is the same reason I don't like font size buttons on websites.

All of your use cases could be achieved with a good print stylesheet, some user education (CTRL+P, CMD+P), and software for those small number that need it.

(Having said all of that, we created something like this on our own site with Display Suite + CSS. We had other requirements like including multiple pages and customisation output that meant we had to. I'm happy to share details on that if people contact me.)

**Comment by Wongad** [comment]
Thanks @mgdhs,
I'm not a big fan of enabling this module myself but there's valid business and legal requirements to produce the consistency of PDF publications as a more formal document. This is more satisfying the needs of government and legal formalities for publications.

Here are some points to what you've mentioned:
- It can be achieved with a proper (simple and short) print CSS - think of it as part of a responsive design, where a page is simply one more device.
  - Agreed, but this is also what the Print module could do.
- A dedicated print page is old school and has been phased out in the industry.
  - Not really, unless you're talking about only tech-savvy users. There's always preference for printed materials. Taking a quote out from the [Design School](https://designschool.canva.com/blog/print-vs-web/) to look at consistency for layout:

> Each approach also has its own unique layout requirements. For print, all information must be presented within the constraints of the printing surface, whereas for the web, designers have almost unlimited flexibility to organize, arrange, and filter information. 
- How do you manage the analytics and navigation between print and non-print, and maybe even separate mobile pages. What happens when someone links or searches and gets directly to the print page?
  - You can measure the analytics between print and non-print pages easier with the Print module as it will treat the PDF file as a download. This will further assists us in understanding the user's preference in wanting to view the page as well as download/print the page. (Could check [Google Analytics - Additional downloads tracking](https://support.google.com/analytics/answer/1012044?hl=en))There's no way that I know if we're able to track "print" from browser in Google Analytics. For users who get directly to the print page, this will then be treated as a download and automatically recorded in Google Analytics.
- "Users spend most of their time on other websites". If this is a browser or software function that a small percentage of users need, they can manage that themselves. This is the same reason I don't like font size buttons on websites.
  - Agreed, but 40% of Internet Explorer users is not really a small percentage.

Thank you once again for your input and my comments are in no way disputing what you've put across. I know the possibilities with a print stylesheet but sometimes having a module to further enhance the functionality may provide a better usability experience.

**Comment by mgdhs** [comment]
We're on the same page, I think this is a good discussion :)

I have something you might like - if you're interested in tracking what users are currently printing on your site, below is some JS that does exactly this. This is something we've been using for the past couple of years on our site. I cobbled it together from a variety of articles. It worked across a range of browsers (pre-Edge), so seemed to be reasonable accurate. It is quite surprising what people are printing:

```
(function() {
  window.beforePrintSeen = window.beforePrintSeen ? window.beforePrintSeen : false;
  var beforePrint = function() {
      if (!window.beforePrintSeen) {
          window.beforePrintSeen = true;
          ga('send', 'event', 'Print', 'Print', document.title);
      }
  };
  if (typeof window.onbeforeprint !== "undefined") {
      window.onbeforeprint = beforePrint;
  } else if (window.matchMedia) {
      var printMediaQuery = window.matchMedia('print');
      printMediaQuery.addListener(function(q) {
          if (q.matches) {
              beforePrint();
          }
      });
  }
}());
```

By 'dedicated print page' I didn't mean ruling out print altogether. I meant having a 'screen' page (at one URL) and a 'print' page at a different URL - the print one even displays on the screen and still requires the user to initiate sending it to their printer.

My remaining _purest_ concern is that developers could be lazy with this module and not put a proper print CSS on their site. You only have to look through the [list of sites on govCMS](https://www.govcms.gov.au/about/news/govcms-sites-and-agencies), find a content page, and go to the print preview to see how often this gets missed. I'll admit it is easy the last thing on your list to build and out of sight.

**Comment by Wongad** [comment]
I'm probably one of those lazy developers who have done this. Which comes to the point of having this module as an easy option to define the print styles.

Thanks for the script provided, I've add that in and could see the event stats coming in straightaway from my real-time stats. Excellent!

At the end of the day we'll still require to have the module enable in order to satisfy the business needs. Just seeking any opinions if there's any issue with enabling this module or if this is out of considerations for govCMS.

**Comment by fiasco** [comment]
Will adding the print module really solve the problem? The PDF part of the print module still requires a PDF binary to run server side to render the pages to PDF. None of which are perfect. Each have their own pros and cons which makes supporting them a nightmare. Pushing this to the client-side not only puts less stress on the server side but also does a perfect job of converting a page to PDF.

IMO, a prerequisite for govCMS pdf support would be to have a good print CSS out of the box. But in order to do that, we need to have better base theme consistency and a framework that adopters are encouraged to use. That seems quite awhile away before we could reach that point.

**Comment by Wongad** [comment]
Thanks @fiasco 
I guess we'll work on our Print stylesheet to produce the print layout we wanted and we'll wait till govCMS has the theme consistency and framework before requesting for this module again.
