### ISSUE TITLE
Blacklisted fast 404 file extensions

### ISSUE THREAD

**Issue by steveworley** [govCMS/GovCMS7#251]
When accessing paths that end in the extensions defined in `404_fast_paths` you are presented with a generic 404 page that cannot be controlled by site owners.

![fast404_paths](https://cloud.githubusercontent.com/assets/1840912/15235899/d5e54114-1902-11e6-9cad-22a928576cde.png)

This has negative impacts for user experience. It should be customisable and give site owners the ability to:
- theme the 404 page to match the styleguide
- place custom analytics tracking to help inform decisions especially around missing files
- provide options for visitors who reach a missing file

**Comment by fiasco** [comment]
I don't think there is anything we could do in the distribution without exposing more of the Drupal bootstrap to the page load which would result in a performance degrade. Thats worth noting too as a UX downside. Knowing the file isn't there sooner has its advantages especially if the file isn't going to be delivered anyway.

Pretty 404 pages for missing files don't apply in all contexts either. Missing images, js and css files in most cases are not being directly requested but are being loaded in as assets to an HTML page. As this would benifit more specifically .pdf, .doc, .txt and .xls files, if any solution would be implemented it should ideally be limited to these file types.

In order to keep Drupal's bootstrap to a minimum for this sort of thing, one option could be to reference a html file on disk in the settings.php as the 404 page for specific extensions. From a govCMS SaaS standpoint, that html file would need to reside in the site's theme folder. Then it would be up to the agency to maintain their 404 page in their site theme.

Would that work?

**Comment by Podgkin** [comment]
Settings.php defines:

`$conf['404_fast_paths'] = '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i';`

so this problem doesn't effect pdf, .doc and .xls. 

The most common time you'll run into this is if there was an image, txt or flash file which was deleted without a redirect being created. While you're right that these are often part of other content, that will not always be the case for things like infographics, text checklists or something like flash based e-learning modules.

 The second scenario is that you migrated to govCMS from a different platform and don't have redirects for all your old URLs, in which case you could well need better 404s for at least cgi, dll, bat and asp, and possibly exe and the images and flash to boot.   

Assuming all of those extensions were pointing to the html page you suggest, then yes your proposed solution would improve the user experience.

**Comment by steveworley** [comment]
@fiasco that proposed solution is what I was thinking, a way to define a custom 404 page in the sites theme and then reference that markup when delivering a fast 404.

**Comment by fiasco** [comment]
We're going to implement this in the SaaS product and not in the distribution. We'll leave this ticket open to keep you posted (or move to the community forums). I'll remove this from the milestone for the release.

**Comment by fiasco** [comment]
This is resolved and now implemented in the SaaS distribution.
