### ISSUE TITLE
Update Metatag to latest release

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#255]
Afternoon all,

We're working on a Factory site where we obviously don't have the ability to access the broader codebase.  We need to be able to verify domain ownership for things like Google Webmaster Tools and Bing etc.  We'd usually achieve this with files in the docroot or with the [Site verification module](https://www.drupal.org/project/site_verify).

If no one has any suggestions on how we can get this done on Factory with the current distro, we'd like to see the above module in the distro.

Anyone got any thoughts?

**Comment by marblegravy** [comment]
The more recent versions of Metatag (since ~ 7.x-1.5) supports the site verification tags OOTB with the  Metatag: Verification submodule.

GovCMS is up to version 1.4, but I'd imagine the step up to 1.5 wouldn't be too drastic.

I guess as long as the patch that's currently being applied to metatag (https://www.drupal.org/files/issues/support-all-attributes-1970362.pass_.patch) is compatible with the current major release we should just update that (perhaps even to the most recent 1.14 version) and your problem would be solved without having to add in an additional module, right?

**Comment by fiasco** [comment]
I like the idea of upgrading to Metatag 1.5. Lets get a PR in for that.

**Comment by marblegravy** [comment]
Is there a reason not to update it to the latest stable version?

**Comment by marblegravy** [comment]
Ah, I see that the metatag issue has been around for a while. I found issue #166 that gives a lot more background on why metatag is stuck. 

Even updating to 1.5 needs attention paid to the patch:
`projects[metatag][patch][] = "https://www.drupal.org/files/issues/support-all-attributes-1970362.pass_.patch"`

**Comment by Feng-Shui** [comment]
Hi guys, thanks for your suggestions.  I'm currently on leave welcoming a new addition to our family, I'll pick this up in a week or two.

**Comment by Feng-Shui** [comment]
I'm picking this on up again - will work on a PR for 1.5.

**Comment by fiasco** [comment]
Merged, thanks for the commit!
