### ISSUE TITLE
As a publishing team member, I would like Workbench Moderation to send emails when content changes status

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#279]
A request from an agency to allow roles and/or specific group email box to receive notification when content changes states in the workflow process.

**Acceptance Criteria**
- Allow editing of email templates
- Separate email templates per stage/transition

Any thoughts on best implementation?

**Comment by pandaskii** [comment]
1. Workbench Email

https://www.drupal.org/project/workbench_email

![workbenchemailadminpanel](https://cloud.githubusercontent.com/assets/1326673/16409517/44ea7890-3d61-11e6-90be-430e7ab79054.png)
1. Setup workbench with rules (in govCMS core)

**Comment by simesy** [comment]
Option 2. above is SAAS friendly - just needs Rules UI enabled.

**Comment by paulkilla** [comment]
Can confirm Option 2 works in SaaS, have implemented on a number of sites (based on transition, and role of users).

**Comment by paulkilla** [comment]
So would be good to add this to some sort of docs site or the community?

### Enable required modules
1. Ensure that the `workbench_moderation` and the `rules`/`rules_admin` modules are enabled. (By default all are except `rules_admin` - Rules UI)

### Configure Rules
1. Visit `/admin/config/workflow/rules` and select 'Add new rule'
2. Give it a name, and optional tags.  Set the React on event to be `After moderation transition`, under the Node section.
3. Add a Condition by selecting 'Add condition'. Select `content is using workbench moderation`.
4. Add a 'and' condition by selecting 'Add and'.
5. Add another Condition by selecting 'Add condition' next to the 'AND'. This time select `Content's previous moderation state`. Then select which state you want to monitor. e.g. if you want from `draft` to `needs review` then for previous state, select `draft` for the previous state.
6. Repeat the step 5, but instead of selecting the previous state, you want to select `Content's current moderation state`, then for the current state, select the state you wish to send e-mails for. e.g. `needs review`
7. Create an Action by selecting 'Add action'.
8. Select the action `Send mail to all users of a role`. Then select all the roles you want to receive emails for the conditions listed above.  Give the e-mail a subject, and some content, allowing you to use replacement patterns to print node titles, urls etc.

### Celebrate
- Just a note that you can obviously set more conditions here, so e.g. content is of type abc. etc.
- Attaching a screenshot of what my setup looks like, which is a working setup.
  <img width="2515" alt="email_rule" src="https://cloud.githubusercontent.com/assets/6803470/18114905/50cafde8-6f7e-11e6-9a60-80de947d2410.png">
