### ISSUE TITLE
Vision 6 Integration

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/GovCMS7#336]
We have a agencies interested in being able to integrate with Vision6. Salsa has a sandbox project here that's being finished off for another agency, https://www.drupal.org/sandbox/salsadigital/2673750. Once this is complete, if there's some interest, we can add it to the make file and PR.

**Comment by aleayr** [comment]
Hey Kurt, what's this integration doing? Is it just collecting subscribers and sending them to Vision6, or deeper than that?

**Comment by kurtfoster** [comment]
@aleayr , there are two part to it. There is a submodule that provides one or more subscription blocks, that creates a custom block which can be placed anywhere and allows users to subscribe to 1 or more lists. 
The other section provides configuration that allows admins to add several fields in the publishing vertical tab on a content type. When they are used on a specific node, that node can auto create a newsletter in Vision 6 and send it out to a mailing list.

**Comment by Podgkin** [comment]
This  seems very similar to https://github.com/govCMS/govCMS/issues/244  

Why would govCMS support a custom vendor specific mailing list integration, rather than a more generic subscription model?

**Comment by aleayr** [comment]
At this stage, by way of explanation, I'm not keen to support specific vendor modules in this type of category due to the plethora of options available and all companies would then want their modules on the distribution.

I'm going to suggest that theme level (JavaScript or PHP-based APIs), or iframe/embed options are going to be the best options going forward.

I have future plans in this space to potentially allow vendor modules on a site-by-site basis but keeping them out of the main distribution, but relies on some hosting advances on the SaaS platform with Acquia, and this isn't a short term change unfortunately.

In the meantime, I'm going to close this off.
