### ISSUE TITLE
As a site builder I would like to allow users to download webform output as a word document

### ISSUE THREAD

**Issue by garthpowell** [govCMS/GovCMS7#360]
When a user submits a form I would like to trigger a download of a word file from a template that includes word formatting and form tokens  as opposed to triggering an email submission.

**Comment by Podgkin** [comment]
I am not sure I fully understand the end user requirements, what does their user journey look like?   

I presume our user makes selections in the webform, the output changes depending on their selections, and then they need to save that output for later use. Is that correct?  Does the output have to be a word document? What goal are they trying to achieve that nessecitates a specific file format?

**Comment by garthpowell** [comment]
In this specific journey a user would fill out the form which then populates part of the returned output, in this case a word file.

So instead of the user submitting the form and an email being sent to a specified recipient, the user submits the form and a download for a word file is triggered instead which includes their input and content from a template. 

The reason for word is that we wish the user to be able to edit the output after receiving the downloaded file.

**Comment by DJMyles** [comment]
Hi Garth,

Have you investigated the possibility of fillable PDF's meeting your requirements?

https://acrobat.adobe.com/au/en/acrobat/how-to/create-fillable-pdf-forms-creator.html

**Comment by garthpowell** [comment]
The fillable PDF would be an easier solution but our requirement is that users can edit the output.

**Comment by Podgkin** [comment]
This is sounding quite familiar, we have a custom bespoke system which "intelligently" prefills word documents as "pseudo smart-forms". In my personal opinion they are all workarounds for poor business processes and should all be fully digitised.  In general if we interupt a webform halfway to switch back to word documents, it sounds like an admission that the webform sucks.   

So to take it one step further, why does the user actually want a half prefilled word document?  

Is it because they can't log in and save their details for later? Or maybe because the next part of the form is filled out by someone else elsewhere? What problem is the word document solving? Can it be solved better in a different way?

**Comment by garthpowell** [comment]
Hi
I was trying to avoid detailing our specific requirements in order to keep this story as high level as possible but in doing so I think this has caused some confusion.

Our requirement is for webform to generate an agreement that 2 parties can print and sign.

Basin steps
1. User fills out first and second party details as well as some other information regarding the agreement. There is some basic conditional logic in the form.
2. User submits the form and a receives the downloaded word file with their input and the agreement details
3. User can modify the output as its in word format
4. User prints and both parties sign.

**Comment by Podgkin** [comment]
No worries mate, just trying to figure out if we all have common requirements. There is the [Webform Document](https://www.drupal.org/project/webform_document) module, but it requires a CDE package which is a pretty huge dependency to introduce into the distribution.   I'd suggest you're probably better off doing this client side through your theme layer using the [jQuery Word  Export plugin](https://github.com/markswindoll/jQuery-Word-Export)

**Comment by garthpowell** [comment]
Yes I have tested the webform document module and it works albeit a bit unreliable when modifying templates. The jquery plugin looks promising too. There is also an option for PHP to word as well.

I assumed that this requirement would most likely not be shared with community but it was worth putting out there.

**Comment by aleayr** [comment]
Hi @garthpowell 

I had your email forwarded to me internally as well in relation to this one, apologies that I've been flat strap and hadn't replied at this point.

I'm interested in some sort of conditional logic for webforms, but the general use case I'm hearing from agencies, is more like a wizard with either a traditional form-to-email output, or presenting content dependent on the answers provided.

The use case of then exporting the output in a different hasn't been raised until this point though.

@Podgkin Looks like Webform Document only requires CDE if you want to export to PDF, if I'm reading the project page correctly? Can you confirm? That said, multiple output options would probably be desirable, rather than a single one.

I'm open to canvassing support for this though.

**Comment by garthpowell** [comment]
You are correct, the CDE is only required for the word to PDF conversion which is not part of our requirements

As I stated earlier I was trying not to be too explicit with the requirements but I think I just sounded like a crazy person.

**Comment by Podgkin** [comment]
Yep, only required for PDFs. The maintenance status is also pretty questionable though, there is no stable version, the last commit was a year ago and there are quite major open issues with simple fixes which have gone unanswered for several months.  It is the best standalone vendorless webform to word module, but it is not that great. 

 There are many implementations of this concept, numerous javascript libraries and a number of 3rd party services and APIs for achieving this.  I have successfully used the [livedox](https://www.drupal.org/project/livedocx) module to achieve this before, but it is vendor specific and livedocx is now being phased out. I was mainly mentioning those two earlier solutions as examples to highlight the two approaches of module or client side,   

If this was to be done at the module level there is a broader platform question about how far govCMS extends. This kind of thing is straying into the realm of smart form providers and CRM. We keep being told we should look to market solutions for functionality not related to content management.  

Again I think in this instance the client side approach is likely to get the best resolution in the shortest time frame, as it gives Garth control over which library to use and how to use it. I like the jQuery approach, but in addition to those mentioned there are also options like [DOCX.js](https://github.com/stephen-hardy/DOCX.js) and [googoose.js](https://github.com/aadel112/googoose).

**Comment by garthpowell** [comment]
Hi
Thank you to everyone for you advice. I agree a client side resolution is the best way to go for this due to time frames and am currently preparing to engage the marketplace.

I guess this is the point where I close the request,.

Cheers
Garth
