### ISSUE TITLE
Research: As a content author, I'd like to upload a document to the private space to control access

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#364]
# Full Description

This is predominantly a placeholder user story for tracking the potential for including, or making steps towards, authenticated access to sites or subsites on the govCMS platform.
# Acceptance Criteria
- Ensure uploaded documents are not accessible via direct links
- Ensure user experience to upload private documents is intuitive

- Documents should not appear in search results (eg, Drupal, Google, Solr, etc)
# Caveat

The existence of this user story does not indicate a definitive timeframe for inclusion, nor that it will actually be implemented.

**Comment by mgdhs** [comment]
We have a similar requirement from a business area. We said we couldn't do it in govCMS, so are using a separate bespoke system (which keeps breaking).

Our story was something like: as a document owner, I'd like to restrict access to documents to a select group of users (eg, a vendor), so that the documents can be easily and cheaply distributed. This might be a bit different, as our 'user' of the document was a list of people from the public. Managing these accounts or giving them Drupal accounts was daunting.

I'd add these acceptance criteria:
- Documents should not appear in search results (eg, Drupal, Google, Solr, etc)

If you are talking about restricted-public-user-access to the documents, then I'd also add:
- User accounts for access should not provide publishing access
- User accounts can be managed by a non-publishing govCMS user

**Comment by Podgkin** [comment]
I like the idea, but I see two issues: 
1. govCMS  is not security rated for making **anything** truly private, so there would have to be some definition around how much privacy is expected vs how much is technically possible. 
2. This is well into records management land.   If we are doing document management now, how far are we taking it? 

So my questions are: 
1. Who are the users? Internal or external? Are these departmental staff with a code of conduct to uphold,  or are we talking about authenticating the general public?  
2. What level of security is required for these documents? Who are we hiding them from, and why?  
3. Do we need to manage document revisions?  Are we integrating and syncing with existing EDRMS? 

For a full records management solution, you'd probably want something like [filedepot](https://www.drupal.org/project/filedepot) with [organic groups](https://www.drupal.org/project/og). If you were really keen you could have AD integration with [LDAP for OG](https://www.drupal.org/node/1443428), which would make anyone with internal distributed authoriship very happy. Using filedepot might also solve [issue 362](https://github.com/govCMS/govCMS/issues/362).   

If you just want a basic out-of-the-box solution today, just use trim links.  You can use existing access controls to limit who can see the link, only people with the right permissions in the EDRMS can actually open the files. and the revisions are managed for you.  If you have external users you can do a similar thing thing with invite only google docs.

**Comment by mpigott** [comment]
Hi everyone, I recently came across the requirement to publish private files because a business area wants to make sure no one can access files before an embargo time. I think @aleayr's user story matches our requirement.

**Comment by tobybellwood** [comment]
Private File Systems are now available in govCMS SaaS.
