### ISSUE TITLE
Twitter Block module - Twitter widgets deprecated

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#370]
We have found Twitter has depreciated widget ID and declared "you’ll never need another widget ID again" (REF: https://blog.twitter.com/2016/embedding-twitter-timelines-just-got-a-lot-easier). That said it will be a problem for the Twitter Block module to work properly. 

There are discussions on the module's project pages but no official fix has been released at this moment. https://www.drupal.org/node/2751845

A PR with patch will be submitted regarding this issue.

**Comment by aleayr** [comment]
Thanks @jozhao - good work. We'll look at getting this in as soon as possible.

**Comment by kattekrab** [comment]
Any progress here?

Work around seems to be adding a new text format that allows full html in order to embed the new timeline, but that doesn't seem ideal.  Anyone got other / better approaches for working around this?

**Comment by Chris820** [comment]
We've got a home-brewed module that pulls in a Twitter feed via cURL.
It requires a bit of extra effort tho. eg: The Twitter account owner has to set up an app for their account (dev.twitter.com), because there's a whole bunch of ugly oAuth stuff required to make the cURL work.
And CSS is needed for styling too.
It's more of a module for a site builder really. Far from turnkey.
So probably not better than a full html text format.

Edit: spelling

**Comment by tobybellwood** [comment]
Closing - fixed in #400
