### ISSUE TITLE
Error messages on site after install

### ISSUE THREAD

**Issue by ShmurdaHeWr0te** [govCMS/GovCMS7#587]
Standard CMS install with sample data 
PHP 7.1 
Zip was enabled prior to install 
No errors during install 
![drupal](https://user-images.githubusercontent.com/33696761/32847984-5523e068-c9f9-11e7-8d81-261c25f8f630.PNG)

**Comment by rsau** [comment]
Is __govcms_social_links__ module enabled?

**Comment by pandaskii** [comment]
govCMS7 is working well with PHP 5.3~5.6.* but needs more tweaks for PHP 7

Drupal 7 core should be compatible, but the problem is contrib/custom modules. Many modules don't have releases for php7.* and use several old deprecated functions for example "navbar" and this module "govcms_social_links"

Extra care and tests should be taken with PHP 7, for example

- PHP 7 discussion on Drupal https://www.drupal.org/node/2656548

We should probably address this especially during the transition from govCMS7 to govCMS8

**Comment by tobybellwood** [comment]
In Acquia Cloud, all environments are now provisioned as php7.1 by default - you can change them to 5.6 by clicking on "configure"
![image](https://user-images.githubusercontent.com/4373945/33409234-73c173c4-d5ce-11e7-92e8-79c1851b3217.png)

**Comment by tobybellwood** [comment]
Navbar module uses a library callback that can be patched in 
https://www.drupal.org/project/libraries/issues/2779591

**Comment by fubarhouse** [comment]
Duplicate(?) of #649.

There's a fix and a PR in there too (#647).

edit: This issue was raised before #649, however the fix is over there.
