### ISSUE TITLE
What does PHP 7.1 mean to govCMS 7 sites?

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#634]
PHP 5.6 is fading out

Branch | Initial Release | Active Support Until | Security Support Until
-- | -- | -- | --
5.6 * | 28 Aug 2014 | 3 years, 5 months ago | 19 Jan 2017 | 1 year ago | 31 Dec 2018 | in 10 months
7.0 | 3 Dec 2015 | 2 years, 2 months ago | 3 Dec 2017 | 2 months ago | 3 Dec 2018 | in 9 months
7.1 | 1 Dec 2016 | 1 year, 2 months ago | 1 Dec 2018 | in 9 months | 1 Dec 2019 | in 1 year, 9 months
7.2 | 30 Nov 2017 | 2 months ago | 30 Nov 2019 | in 1 year, 9 months | 30 Nov 2020 | in 2 years, 9 months

And Acquia 

PHP 5.6 - Formal retirement announcement pending	Self-service	Q3 2018	Q3 2018

**Comment by tobybellwood** [comment]
Collected issues under https://github.com/govCMS/govCMS/labels/PHP7.1

**Comment by rooby** [comment]
That table of dates is inaccurate. It shows the active support dates in the 'Security Support Until' column. For the actual table see http://php.net/supported-versions.php
5.6 ends security support at the end of 2018.

Still keen to have some information on this though.

What version of PHP does SaaS and PaaS currently run on?
What version(s) of PHP does the GovCMS automated test suite currently run on?

My anecdotal evidence suggests that issues running on PHP 7 should be minimal and should be fairly straight forward to address.

**Comment by tobybellwood** [comment]
Corrected version of the table referenced from above (cut/paste job!):

Branch | Initial Release | Active Support Until | Security Support Until
-- | -- | -- | --
5.6 * | 28 Aug 2014 | 19 Jan 2017 | 31 Dec 2018 |
7.0 | 3 Dec 2015 | 3 Dec 2017 | 3 Dec 2018 |
7.1 | 1 Dec 2016 | 1 Dec 2018 | 1 Dec 2019 |
7.2 | 30 Nov 2017 | 30 Nov 2019 | 30 Nov 2020 |

As for versions,
The current production ACSF php version is 5.6.32
We currently run 5.6.14 on our automated test suite, and we are looking to bring in parallel 7.1 testing.

**Comment by rooby** [comment]
Cool, thanks for the info

**Comment by deepakvasa** [comment]
Hi,
Is there an update to this and release timeline available?

We are considering building a new site using GovCMS and are concerned about maintaining ISM compliance post December 31. 

Ideally, we would like to see GovCMS support the latest PHP version (7.2 at time of writing).

Thanks

**Comment by fubarhouse** [comment]
> Ideally, we would like to see GovCMS support the latest PHP version (7.2 at time of writing).

[Official documentation](https://support.acquia.com/hc/en-us/articles/360005487794-Upgrading-from-PHP-5-6-to-7-1-or-7-2) only supports upgrade paths from:
* `5.6` to `7.0`
* `7.0` to `7.1`
* `7.1` to `7.2`

In addition to this, Drupal is not completely supportive of `7.2` yet.

* [[PHP 7.2] Avoid count() calls on uncountable variable](https://www.drupal.org/node/2885610)
* [[PHP 7] Function each() is deprecated since PHP 7.2; D7](https://www.drupal.org/node/2925449)
* [Unable to update modules due to Archive_Tar incompatibility with PHP 7.2](https://www.drupal.org/node/2946045)
* [Fully support PHP 7.2 in Drupal 7](https://www.drupal.org/node/2947772)

Until `7.2` is completely supported by Drupal 7, govCMS will likely not go near it - and it may not even be a priority until PHP `7.1` becomes a problem (EOL as an example). If it weren't for `5.6` being EOL it's likely support would be maintained by vendors and Drupal itself.

So, December 31 isn't very likely - I'm all for it though.

**Comment by deepakvasa** [comment]
Thanks for the info. Is there any place where the timelines for the upgrade have been published?

**Comment by pandaskii** [comment]
@deepakvasa 

PHP http://php.net/supported-versions.php

Acquia https://support.acquia.com/hc/en-us/articles/360005518633-PHP-5-6-Retirement-FAQ

GovCMS not available yet

@tobybellwood Please correct me if I am wrong

PHP 7.1 is the priority for GovCMS 7 because of the PHP 5.6 EOL

**Comment by fubarhouse** [comment]
I'm not sure how relevant this is to the progress or timeline, but I'll leave this here:

[![image](https://user-images.githubusercontent.com/3070264/42486694-c056699e-8440-11e8-8c8d-b00275910de2.png)](https://docs.acquia.com/acquia-cloud/manage/php/#php-version)

**Comment by tobybellwood** [comment]
thanks @fubarhouse - yeah, that's a fairly big motivator...

**Comment by tobybellwood** [comment]
Just spotted a swathe of PHP7.2 related commits to Drupal 7.x
https://www.drupal.org/project/drupal/issues/2947772
https://cgit.drupalcode.org/drupal?h=7.x

**Comment by fubarhouse** [comment]
Cool - that would cover the basics! After core has adopted support, there's just all the contributed modules to follow along.
