### ISSUE TITLE
Consider using workbench scheduler instead of scheduler workbench integration

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#657]
The [workbench scheduler](https://www.drupal.org/project/workbench_scheduler) module is a more powerful solution than the [scheduler workbench integration](https://www.drupal.org/project/scheduler_workbench) module in that it can handle unpublishing content as well as publishing it (and also any other scheduled workflow state transition).

Neither module has the best maintenance record but I would favour workbench scheduler in that department because it has a larger user base (so more likely to have extra developers step up if required) and scheduler workbench integration did have the unsupported security fix scare a while back, which was fixed by a new maintainer, but then hasn't had any further updates since and is still has the unsupported flag on its project page.

**Comment by pandaskii** [comment]
Current distribution has a few contrib modules in the similar situation and we do need a plan for such modules. Unfortunately, we cannot drag and drop new modules in, then move old modules out easily in such a large distribution especially having a big user base of Sass.

It is a classic question - is is better to repair or replace?

- Do we want to provide an upgrade path from "scheduler workbench" to "workbench scheduler" and depreciate the "scheduler workbench" in a timeframe? 

- Do we want to keep them in parallel?

- Are we good to bump up "workbench_moderation" finally? Or we find another unsupported version with many patches so that it can work with old "workbench_moderation" in distribution

Personally, I cannot see any big advantages adding this module right now. Instead, this reminds me "workbench_moderation" in distribution. Hopefully, we can have some solutions for it

**Comment by rooby** [comment]
The main use case I've had requests for that I don't think can be accomplished with the current module is scheduled unpublishing.

It may be that it's not worth the hassle for D7 but it would definitely be worth considering for D8.

**Comment by invisigoth** [comment]
Scheduled publishing is not yet supported by govCMS8. It has been added to the work backlog and all feasible options will be properly evaluated.

**Comment by tobybellwood** [comment]
We'll certainly add scheduled unpublishing to the wishlist when evaluating d8 workflows.

**Comment by rooby** [comment]
Actually to correct myself, the current scheduling module does support unpublishing, although it is buggy in a few potential configurations and isn't quite as flexible as the other solution.

Should be fine though for D7, especially once those bugs get fixes.

In which case this issue can probably be closed.
